language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit

matrix:
  fast_finish: true
