language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_install:
  - composer self-update

install:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
